[package]
name = "zokute"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
notify = "6"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
sysinfo = "0.39"
tokio = { version = "1", features = ["time"] }
gtk = { version = "0.18", features = ["v3_24"] }
tauri = { version = "2", features = [] }

[dev-dependencies]
tempfile = "3"
